Repository codestates-seb/seb45_main_031, pull requests merged in 2023-08, with the labels that each got.

#12 [FE] Document : FE 개발 환경 세팅
  FE/.eslintrc.json
  FE/.gitignore
  FE/.prettierrc.json
  FE/README.md
  FE/package-lock.json
  FE/package.json
  FE/public/favicon.ico
  FE/public/index.html
  FE/public/logo192.png
  FE/public/logo512.png
  FE/public/manifest.json
  FE/public/robots.txt
  FE/src/App.js
  FE/src/assets/icons/index.js
  FE/src/assets/images/index.js
  FE/src/components/index.js
  FE/src/index.js
  FE/src/pages/index.js
  FE/src/styles/GlobalStyles.js
Labels: Documentation, FE

#26 [BE] Feat : BE 공통 유틸 기능
  server/routine/src/main/java/com/seb45_main_031/routine/audit/Auditable.java
  server/routine/src/main/java/com/seb45_main_031/routine/dto/MultiResponseDto.java
  server/routine/src/main/java/com/seb45_main_031/routine/dto/PageInfo.java
  server/routine/src/main/java/com/seb45_main_031/routine/dto/SingeResponseDto.java
  server/routine/src/main/java/com/seb45_main_031/routine/utils/UriCreator.java
Labels: Feat, BE

#27 [BE] Feat : 공통 예외 처리
  server/routine/src/main/java/com/seb45_main_031/routine/RoutineApplication.java
  server/routine/src/main/java/com/seb45_main_031/routine/exception/BusinessLogicException.java
  server/routine/src/main/java/com/seb45_main_031/routine/exception/ErrorResponse.java
  server/routine/src/main/java/com/seb45_main_031/routine/exception/ExceptionCode.java
  server/routine/src/main/java/com/seb45_main_031/routine/exception/GlobalExceptionHandle.java
  server/routine/src/main/java/com/seb45_main_031/routine/member/entity/Member.java
Labels: Feat, BE

#28 [BE] Feat : Feed(Community) CRUD 기능 구현
  server/routine/src/main/java/com/seb45_main_031/routine/dto/SingeResponseDto.java
  server/routine/src/main/java/com/seb45_main_031/routine/feed/controller/FeedController.java
  server/routine/src/main/java/com/seb45_main_031/routine/feed/dto/FeedDto.java
  server/routine/src/main/java/com/seb45_main_031/routine/feed/entity/Feed.java
  server/routine/src/main/java/com/seb45_main_031/routine/feed/mapper/FeedMapper.java
  server/routine/src/main/java/com/seb45_main_031/routine/feed/repository/FeedRepository.java
  server/routine/src/main/java/com/seb45_main_031/routine/feed/service/FeedService.java
Labels: Feat, BE

#30 [FE] Fix : App.js 공통 Display 설정
  FE/package-lock.json
  FE/package.json
  FE/src/App.js
Labels: FE

#31 [BE] Dev be#15/todo crud
  server/routine/src/main/java/com/seb45_main_031/routine/dto/SingleResponseDto.java
  server/routine/src/main/java/com/seb45_main_031/routine/feed/entity/Feed.java
  server/routine/src/main/java/com/seb45_main_031/routine/member/controller/MemberController.java
  server/routine/src/main/java/com/seb45_main_031/routine/member/entity/Member.java
  server/routine/src/main/java/com/seb45_main_031/routine/todo/controller/TodoController.java
  server/routine/src/main/java/com/seb45_main_031/routine/todo/dto/TodoDto.java
  server/routine/src/main/java/com/seb45_main_031/routine/todo/entity/Todo.java
  server/routine/src/main/java/com/seb45_main_031/routine/todo/mapper/TodoMapper.java
  server/routine/src/main/java/com/seb45_main_031/routine/todo/repository/TodoRepository.java
  server/routine/src/main/java/com/seb45_main_031/routine/todo/service/TodoService.java
Labels: Feat, BE

#34 [FE] Fix : prettier 에러 해결 코드 추가
  FE/.eslintrc.json
Labels: FE

#36 [FE] 할 일 목록 페이지 뷰 및 기능 일부 구현
  FE/.eslintrc.json
  FE/src/App.js
  FE/src/assets/images/index.js
  FE/src/assets/images/memberImg.jpeg
  FE/src/assets/images/trophyLevel1.png
  FE/src/data/dummy.js
  FE/src/pages/index.js
  FE/src/pages/todoPage.js
Labels: Feat, FE

#40 [BE] Feat: Todo Count 기능 구현
  server/routine/src/main/java/com/seb45_main_031/routine/todo/controller/TodoController.java
  server/routine/src/main/java/com/seb45_main_031/routine/todo/dto/TodoDto.java
  server/routine/src/main/java/com/seb45_main_031/routine/todo/entity/Todo.java
  server/routine/src/main/java/com/seb45_main_031/routine/todo/mapper/TodoMapper.java
  server/routine/src/main/java/com/seb45_main_031/routine/todo/service/TodoService.java
Labels: Feat, BE

#38 [FE] Feat : 할 일 작성 페이지 뷰 및 기능 일부 구현
  FE/src/App.js
  FE/src/pages/TodoEditPage.js
Labels: Feat, FE

#43 [BE] Rename : Responses 변수명 단순 수정
  server/routine/src/main/java/com/seb45_main_031/routine/todo/dto/TodoDto.java
  server/routine/src/main/java/com/seb45_main_031/routine/todo/mapper/TodoMapper.java
Labels: BE, Refactoring

#41 [FE] 할 일 목록 페이지의 달성량 게이지 구현
  FE/.eslintrc.json
  FE/src/App.js
  FE/src/pages/todoPage.js
Labels: Feat, FE

#45 [BE} Feat : Tag CRUD 구현
  server/routine/src/main/java/com/seb45_main_031/routine/feed/dto/FeedDto.java
  server/routine/src/main/java/com/seb45_main_031/routine/feed/entity/Feed.java
  server/routine/src/main/java/com/seb45_main_031/routine/feed/mapper/FeedMapper.java
  server/routine/src/main/java/com/seb45_main_031/routine/feedTag/dto/FeedTagDto.java
  server/routine/src/main/java/com/seb45_main_031/routine/feedTag/entity/FeedTag.java
  server/routine/src/main/java/com/seb45_main_031/routine/tag/controller/Controller.java
  server/routine/src/main/java/com/seb45_main_031/routine/tag/dto/TagDto.java
  server/routine/src/main/java/com/seb45_main_031/routine/tag/entity/Tag.java
  server/routine/src/main/java/com/seb45_main_031/routine/tag/mapper/TagMapper.java
  server/routine/src/main/java/com/seb45_main_031/routine/tag/repository/TagRepository.java
  server/routine/src/main/java/com/seb45_main_031/routine/tag/service/TagService.java
Labels: Feat, BE
