Repository codestates-seb/seb45_main_031, pull requests merged in 2023-09, with the labels that each got.

#47 [BE] Feat: Tag Todo Mapping
  server/routine/src/main/java/com/seb45_main_031/routine/todo/dto/TodoDto.java
  server/routine/src/main/java/com/seb45_main_031/routine/todo/entity/Todo.java
  server/routine/src/main/java/com/seb45_main_031/routine/todo/mapper/TodoMapper.java
  server/routine/src/main/java/com/seb45_main_031/routine/todo/service/TodoService.java
Labels: Feat, BE

#52 [FE] Fix : login page 뷰 구현
  FE/src/App.js
  FE/src/assets/images/google.png
  FE/src/pages/LoginPage.js
  FE/src/pages/TodoEditPage.js
  FE/src/pages/todoPage.js
Labels: Feat, FE

#51 [BE] Feat : Tag - Feed Mapping
  server/routine/src/main/java/com/seb45_main_031/routine/feed/dto/FeedDto.java
  server/routine/src/main/java/com/seb45_main_031/routine/feed/entity/Feed.java
  server/routine/src/main/java/com/seb45_main_031/routine/feed/mapper/FeedMapper.java
  server/routine/src/main/java/com/seb45_main_031/routine/feed/service/FeedService.java
  server/routine/src/main/java/com/seb45_main_031/routine/feedTag/repository/FeedTagRepository.java
Labels: Feat, BE

#54 [BE] Add Todo 단일조회 기능 추가
  server/routine/src/main/java/com/seb45_main_031/routine/todo/controller/TodoController.java
  server/routine/src/main/java/com/seb45_main_031/routine/todo/dto/TodoDto.java
  server/routine/src/main/java/com/seb45_main_031/routine/todo/mapper/TodoMapper.java
  server/routine/src/main/java/com/seb45_main_031/routine/todo/repository/TodoRepository.java
  server/routine/src/main/java/com/seb45_main_031/routine/todo/service/TodoService.java
Labels: Feat, BE

#55 [FE] 할 일 목록 페이지, 할 일 작성 페이지 기능 구현
  FE/src/App.js
  FE/src/data/dummy.js
  FE/src/pages/TodoEditPage.js
  FE/src/pages/todoPage.js
Labels: Feat, FE

#56 [FE] Feat : 할 일 수정 페이지 뷰 및 기능 구현
  FE/src/pages/TodoModifyPage.js
Labels: Feat, FE

#57 [FE] Fix : Footer 아이콘 클릭 시 페이지 이동 구현
  FE/src/components/Footer.js
Labels: FE

#58 [FE] Feat : 마이페이지 뷰 및 기능 일부 구현
  FE/src/App.js
  FE/src/assets/images/profile.svg
  FE/src/pages/MyPage.js
Labels: Feat, FE

#59 Feat: SignUppage 뷰 구현
  FE/src/App.js
  FE/src/pages/SignUpPage.js
Labels: Feat, FE

#63 [BE] Feat : Tag CRUD 기능 추가
  server/routine/src/main/java/com/seb45_main_031/routine/exception/ExceptionCode.java
  server/routine/src/main/java/com/seb45_main_031/routine/member/service/MemberService.java
  server/routine/src/main/java/com/seb45_main_031/routine/tag/controller/Controller.java
  server/routine/src/main/java/com/seb45_main_031/routine/tag/controller/TagController.java
  server/routine/src/main/java/com/seb45_main_031/routine/tag/dto/TagDto.java
  server/routine/src/main/java/com/seb45_main_031/routine/tag/entity/Tag.java
  server/routine/src/main/java/com/seb45_main_031/routine/tag/mapper/TagMapper.java
  server/routine/src/main/java/com/seb45_main_031/routine/tag/repository/TagRepository.java
  server/routine/src/main/java/com/seb45_main_031/routine/tag/service/TagService.java
Labels: Feat, BE

#65 :bug: fix: .eslintrc.json_bug
  FE/.eslintrc.json
  FE/package-lock.json
  FE/package.json
  FE/src/pages/TodoModifyPage.js
Labels: Bug, FE

#66 [FE] 할 일 목록, 할 일 작성 및 수정 페이지 일부 수정, 커뮤니티 페이지 뷰 구현
  FE/src/data/tags.js
  FE/src/pages/CommunityPage.js
  FE/src/pages/TodoEditPage.js
  FE/src/pages/TodoModifyPage.js
  FE/src/pages/todoPage.js
Labels: Feat, FE, Advanced

#69 Fix: Header,Footer,Login 수정
  FE/src/components/Footer.js
  FE/src/components/Header.js
  FE/src/pages/LoginPage.js
  FE/src/pages/MyPage.js
Labels: FE

#70 [BE] Feat : 대댓글 기능 구현
  server/routine/src/main/java/com/seb45_main_031/routine/comment/controller/ReplyController.java
  server/routine/src/main/java/com/seb45_main_031/routine/comment/dto/ReplyDto.java
  server/routine/src/main/java/com/seb45_main_031/routine/comment/entity/Comment.java
  server/routine/src/main/java/com/seb45_main_031/routine/feed/dto/FeedDto.java
  server/routine/src/main/java/com/seb45_main_031/routine/feed/mapper/FeedMapper.java
Labels: Feat, BE

#71 [FE] Feat: 마이페이지 페이지 이동 구현
  FE/src/pages/MyPage.js
  FE/src/pages/MyPageEdit.js
Labels: Feat, FE

#73 [FE] Fix: 마이페이지 모달창 닫기 버튼 아이콘 추가
  FE/src/assets/icons/close.svg
Labels: FE

#72 [BE] Feat : Feed에 회원 검증 로직 추가
  server/routine/src/main/java/com/seb45_main_031/routine/comment/controller/CommentController.java
  server/routine/src/main/java/com/seb45_main_031/routine/comment/service/CommentService.java
  server/routine/src/main/java/com/seb45_main_031/routine/feed/controller/FeedController.java
  server/routine/src/main/java/com/seb45_main_031/routine/feed/service/FeedService.java
Labels: Feat, BE

#75 [FE] 할 일 목록, 작성, 수정 파트 리팩토링
  FE/src/data/constants.js
  FE/src/pages/TodoEditPage.js
  FE/src/pages/TodoModifyPage.js
  FE/src/pages/todoPage.js
  FE/src/utils/getDateFormat.js
Labels: FE, Refactoring

#77 [BE] Feat: TodoDto validation
  server/routine/src/main/java/com/seb45_main_031/routine/todo/controller/TodoController.java
  server/routine/src/main/java/com/seb45_main_031/routine/todo/dto/TodoDto.java
  server/routine/src/main/java/com/seb45_main_031/routine/todo/service/TodoService.java
Labels: Feat, BE

#78 [FE] 할 일 목록, 작성, 수정 페이지 및 커뮤니티 목록, 작성 페이지
  FE/package-lock.json
  FE/package.json
  FE/src/App.js
  FE/src/data/constants.js
  FE/src/pages/CommunityEditPage.js
  FE/src/pages/CommunityPage.js
  FE/src/pages/TodoEditPage.js
  FE/src/pages/TodoModifyPage.js
  FE/src/pages/todoPage.js
Labels: Feat, FE, Refactoring, Advanced

#79 [BE] :sparkles: Feat: Todo에 회원검증 로직 및 태그 ID값 가져오기
  server/routine/src/main/java/com/seb45_main_031/routine/todo/controller/TodoController.java
  server/routine/src/main/java/com/seb45_main_031/routine/todo/service/TodoService.java
Labels: Feat, BE

#80 [FE] Feat: 마이페이지 헤더 변경 페이지 라우팅, 헤더 뷰 및 회원탈퇴 모달창 구현
  FE/src/App.js
  FE/src/assets/icons/back.svg
  FE/src/components/MyPageHeader.js
  FE/src/index.js
  FE/src/pages/HomeTest.js
  FE/src/pages/MyPage.js
  FE/src/pages/MyPageEdit.js
  FE/src/pages/ProfileLayout.js
  FE/src/pages/RootLayout.js
Labels: Feat, FE

#81 [FE] 할 일, 커뮤니티 통합 수정
  FE/src/components/ErrorModal/index.js
  FE/src/components/FeedCard/Comment.js
  FE/src/components/FeedCard/CommentCreate.js
  FE/src/components/FeedCard/Comments.js
  FE/src/components/FeedCard/PostContents.js
  FE/src/components/FeedCard/PostUser.js
  FE/src/components/FeedCard/index.js
  FE/src/components/ModalBackground/index.js
  FE/src/components/TagModal/index.js
  FE/src/components/TodoCard/index.js
  FE/src/data/dummy.js
  FE/src/pages/CommunityEditPage.js
  FE/src/pages/CommunityPage.js
  FE/src/pages/TodoEditPage.js
  FE/src/pages/TodoModifyPage.js
  FE/src/pages/todoPage.js
Labels: Bug, FE, Refactoring, Advanced

#82 [FE] 멘토님 피드백 반영
  FE/src/components/Footer.js
  FE/src/components/Header.js
  FE/src/pages/SignUpPage.js
Labels: FE

#83 [FE] 할 일 작성, 수정 / 커뮤니티 작성 이동 수정
  FE/src/components/Footer.js
  FE/src/pages/CommunityPage.js
  FE/src/pages/TodoEditPage.js
  FE/src/pages/TodoModifyPage.js
  FE/src/utils/conutContentLength.js
Labels: Feat, FE, Advanced

#90 [BE] Feat : Like CRUD 기능 구현
  server/routine/src/main/java/com/seb45_main_031/routine/feed/controller/FeedController.java
  server/routine/src/main/java/com/seb45_main_031/routine/feed/dto/FeedDto.java
  server/routine/src/main/java/com/seb45_main_031/routine/feed/entity/Feed.java
  server/routine/src/main/java/com/seb45_main_031/routine/feed/mapper/FeedMapper.java
  server/routine/src/main/java/com/seb45_main_031/routine/feed/service/FeedService.java
  server/routine/src/main/java/com/seb45_main_031/routine/feedLike/controller/FeedLikeController.java
  server/routine/src/main/java/com/seb45_main_031/routine/feedLike/dto/FeedLikeDto.java
  server/routine/src/main/java/com/seb45_main_031/routine/feedLike/entity/FeedLike.java
  server/routine/src/main/java/com/seb45_main_031/routine/feedLike/mapper/FeedLikeMapper.java
  server/routine/src/main/java/com/seb45_main_031/routine/feedLike/repository/FeedLikeRepository.java
  server/routine/src/main/java/com/seb45_main_031/routine/feedLike/service/FeedLikeService.java
Labels: Feat, BE

#92 [BE] Feat: Todo 할 일 여러 개 등록 API 추가
  server/routine/src/main/java/com/seb45_main_031/routine/todo/controller/TodoController.java
  server/routine/src/main/java/com/seb45_main_031/routine/todo/dto/TodoDto.java
  server/routine/src/main/java/com/seb45_main_031/routine/todo/entity/Todo.java
  server/routine/src/main/java/com/seb45_main_031/routine/todo/mapper/TodoMapper.java
  server/routine/src/main/java/com/seb45_main_031/routine/todo/repository/TodoRepository.java
  server/routine/src/main/java/com/seb45_main_031/routine/todo/service/TodoService.java
Labels: Feat, BE, Refactoring

#95 [BE] 댓글 & 대댓글 / 커뮤니티 피드 리팩토링
  server/routine/src/main/java/com/seb45_main_031/routine/comment/controller/CommentController.java
  server/routine/src/main/java/com/seb45_main_031/routine/comment/controller/ReplyController.java
  server/routine/src/main/java/com/seb45_main_031/routine/comment/dto/CommentDto.java
  server/routine/src/main/java/com/seb45_main_031/routine/comment/dto/ReplyDto.java
  server/routine/src/main/java/com/seb45_main_031/routine/comment/entity/Comment.java
  server/routine/src/main/java/com/seb45_main_031/routine/comment/mapper/CommentMapper.java
  server/routine/src/main/java/com/seb45_main_031/routine/comment/service/CommentService.java
  server/routine/src/main/java/com/seb45_main_031/routine/feed/controller/FeedController.java
  server/routine/src/main/java/com/seb45_main_031/routine/feed/dto/FeedDto.java
  server/routine/src/main/java/com/seb45_main_031/routine/feed/entity/Feed.java
  server/routine/src/main/java/com/seb45_main_031/routine/feed/mapper/FeedMapper.java
  server/routine/src/main/java/com/seb45_main_031/routine/feed/service/FeedService.java
  server/routine/src/main/java/com/seb45_main_031/routine/feedLike/controller/FeedLikeController.java
  server/routine/src/main/java/com/seb45_main_031/routine/feedLike/service/FeedLikeService.java
Labels: BE, Refactoring

#87 [FE] Feat: 마이페이지 - 내 게시물 조회 컴포넌트 추가, 레이아웃 일부 수정
  FE/src/data/dummy.js
  FE/src/pages/MyPage.js
Labels: Feat, FE

#97 [FE] 배포 시 화면이 덜 보이는 문제 해결
  FE/src/pages/TodoEditPage.js
  FE/src/pages/TodoModifyPage.js
Labels: Bug, FE

#98 [FE] 할 일 페이지에 token 관련 추가
  FE/src/pages/TodoEditPage.js
  FE/src/pages/TodoModifyPage.js
  FE/src/pages/todoPage.js
Labels: Feat, FE

#96 [FE] Feat : LoginPage 유효성
  FE/src/components/Footer.js
  FE/src/pages/LoginPage.js
Labels: Feat, FE

#100 [BE] Feed -> Todo Mapping
  server/routine/src/main/java/com/seb45_main_031/routine/feed/dto/FeedDto.java
  server/routine/src/main/java/com/seb45_main_031/routine/feed/entity/Feed.java
  server/routine/src/main/java/com/seb45_main_031/routine/feed/mapper/FeedMapper.java
  server/routine/src/main/java/com/seb45_main_031/routine/feed/service/FeedService.java
Labels: Feat, BE

#102 [BE] Feat: Add todo valid
  server/routine/src/main/java/com/seb45_main_031/routine/todo/dto/TodoDto.java
Labels: Feat, BE, Refactoring

#103 [BE] Feat: Add Feed valid
  server/routine/src/main/java/com/seb45_main_031/routine/feed/dto/FeedDto.java
Labels: Feat, BE, Refactoring

#105 [FE] Token 관련 코드 수정
  FE/src/pages/TodoEditPage.js
  FE/src/pages/TodoModifyPage.js
  FE/src/pages/todoPage.js
  FE/src/utils/countContentLength.js
Labels: Bug, FE

#104 [FE] Feat: SignupPage 유효성 검사
  FE/src/assets/images/communityB.png
  FE/src/assets/images/listB.png
  FE/src/assets/images/mypageB.png
  FE/src/assets/images/writeB.png
  FE/src/pages/SignUpPage.js
Labels: Feat, FE

#113 [BE] Feat : Member 기능 추가
  server/routine/src/main/java/com/seb45_main_031/routine/exception/ExceptionCode.java
  server/routine/src/main/java/com/seb45_main_031/routine/member/controller/MemberController.java
  server/routine/src/main/java/com/seb45_main_031/routine/member/dto/MemberDto.java
  server/routine/src/main/java/com/seb45_main_031/routine/member/entity/Member.java
  server/routine/src/main/java/com/seb45_main_031/routine/member/repository/MemberRepository.java
  server/routine/src/main/java/com/seb45_main_031/routine/member/service/MemberService.java
Labels: Feat, BE

#114 [BE] Feat : Member Feed 조회 기능
  server/routine/src/main/java/com/seb45_main_031/routine/feed/controller/FeedController.java
  server/routine/src/main/java/com/seb45_main_031/routine/feed/repository/FeedRepository.java
  server/routine/src/main/java/com/seb45_main_031/routine/feed/service/FeedService.java
  server/routine/src/main/java/com/seb45_main_031/routine/member/controller/MemberController.java
  server/routine/src/main/java/com/seb45_main_031/routine/member/entity/Member.java
  server/routine/src/main/java/com/seb45_main_031/routine/member/service/MemberService.java
Labels: Feat, BE

#115 [BE] Feat : Member exp/level 기능 추가
  server/routine/src/main/java/com/seb45_main_031/routine/member/dto/MemberDto.java
  server/routine/src/main/java/com/seb45_main_031/routine/member/entity/Member.java
  server/routine/src/main/java/com/seb45_main_031/routine/todo/service/TodoService.java
Labels: Feat, BE, Advanced

#116 [BE] Feat : Member 이미지 업로드 기능
  server/routine/build.gradle
  server/routine/src/main/java/com/seb45_main_031/routine/exception/ExceptionCode.java
  server/routine/src/main/java/com/seb45_main_031/routine/exception/GlobalExceptionHandle.java
  server/routine/src/main/java/com/seb45_main_031/routine/image/AwsS3Config.java
  server/routine/src/main/java/com/seb45_main_031/routine/image/S3FileUploadService.java
  server/routine/src/main/java/com/seb45_main_031/routine/member/controller/MemberController.java
  server/routine/src/main/java/com/seb45_main_031/routine/member/dto/MemberDto.java
  server/routine/src/main/java/com/seb45_main_031/routine/member/entity/Member.java
  server/routine/src/main/java/com/seb45_main_031/routine/member/service/MemberService.java
  server/routine/src/main/resources/application.yml
Labels: Feat, BE, Advanced

#106 [FE] Refactor: 멘토링 피드백 리팩토링
  FE/src/pages/LoginPage.js
  FE/src/pages/SignUpPage.js
Labels: FE, Refactoring

#120 [BE] Fix : 각 도메인 memberId 검증 로직 수정
  server/routine/src/main/java/com/seb45_main_031/routine/comment/controller/CommentController.java
  server/routine/src/main/java/com/seb45_main_031/routine/comment/service/CommentService.java
  server/routine/src/main/java/com/seb45_main_031/routine/feed/controller/FeedController.java
  server/routine/src/main/java/com/seb45_main_031/routine/feed/service/FeedService.java
  server/routine/src/main/java/com/seb45_main_031/routine/feedLike/controller/FeedLikeController.java
  server/routine/src/main/java/com/seb45_main_031/routine/feedLike/service/FeedLikeService.java
  server/routine/src/main/java/com/seb45_main_031/routine/todo/controller/TodoController.java
  server/routine/src/main/java/com/seb45_main_031/routine/todo/service/TodoService.java
Labels: BE, Refactoring

#121 [FE] Feat: 마이페이지 정보 수정 - 사용자 닉네임 변경 기능 구현 및 레이아웃 수정
  FE/src/pages/MyPageEdit.js
Labels: Feat, FE

#125 [BE] Feat : TodoStorage CRUD 구현
  server/routine/src/main/java/com/seb45_main_031/routine/exception/ExceptionCode.java
  server/routine/src/main/java/com/seb45_main_031/routine/todoStorage/controller/TodoStorageController.java
  server/routine/src/main/java/com/seb45_main_031/routine/todoStorage/dto/TodoStorageDto.java
  server/routine/src/main/java/com/seb45_main_031/routine/todoStorage/entity/TodoStorage.java
  server/routine/src/main/java/com/seb45_main_031/routine/todoStorage/mapper/TodoStorageMapper.java
  server/routine/src/main/java/com/seb45_main_031/routine/todoStorage/repository/TodoStorageRepository.java
  server/routine/src/main/java/com/seb45_main_031/routine/todoStorage/service/TodoStorageService.java
Labels: Feat, BE, Advanced

#127 [BE] Feat : SavedTodo CRUD 구현
  server/routine/src/main/java/com/seb45_main_031/routine/exception/ExceptionCode.java
  server/routine/src/main/java/com/seb45_main_031/routine/savedTodo/controller/SavedTodoController.java
  server/routine/src/main/java/com/seb45_main_031/routine/savedTodo/dto/SavedTodoDto.java
  server/routine/src/main/java/com/seb45_main_031/routine/savedTodo/entity/SavedTodo.java
  server/routine/src/main/java/com/seb45_main_031/routine/savedTodo/mapper/SavedTodoMapper.java
  server/routine/src/main/java/com/seb45_main_031/routine/savedTodo/repository/SavedTodoRepository.java
  server/routine/src/main/java/com/seb45_main_031/routine/savedTodo/service/SavedTodoService.java
Labels: Feat, BE, Advanced

#129 [BE] Refactor : 피드, 댓글 @NotNull 애너테이션 삭제
  server/routine/src/main/java/com/seb45_main_031/routine/comment/dto/CommentDto.java
  server/routine/src/main/java/com/seb45_main_031/routine/feed/dto/FeedDto.java
Labels: BE, Refactoring

#132 [BE] Feat : 로그인 인증 MemberInfo 정보 추가
  server/routine/src/main/java/com/seb45_main_031/routine/auth/handler/CustomAuthenticationSuccessHandler.java
  server/routine/src/main/java/com/seb45_main_031/routine/auth/userDetailsService/CustomUserDetailsService.java
Labels: Feat, BE

#130 [FE] Feat : 마이페이지 - 회원 조회 기능
  FE/src/pages/MyPage.js
Labels: Feat, FE

#137 [Be] Feat : AccessToken 검증 예외 추가
  server/routine/src/main/java/com/seb45_main_031/routine/auth/filter/JwtVerificationFilter.java
  server/routine/src/main/java/com/seb45_main_031/routine/auth/handler/CustomAuthenticationEntryPoint.java
  server/routine/src/main/java/com/seb45_main_031/routine/auth/utils/ErrorResponder.java
Labels: Feat, BE

#138 [BE] Feat : TodoStorage 기능 추가 및 SavedTodo 로직 변경
  server/routine/src/main/java/com/seb45_main_031/routine/savedTodo/mapper/SavedTodoMapper.java
  server/routine/src/main/java/com/seb45_main_031/routine/todoStorage/dto/TodoStorageDto.java
  server/routine/src/main/java/com/seb45_main_031/routine/todoStorage/entity/TodoStorage.java
  server/routine/src/main/java/com/seb45_main_031/routine/todoStorage/mapper/TodoStorageMapper.java
Labels: Feat, BE

#139 [BE] Refactor: todo tag refactor
  server/routine/src/main/java/com/seb45_main_031/routine/todo/controller/TodoController.java
  server/routine/src/main/java/com/seb45_main_031/routine/todo/dto/TodoDto.java
  server/routine/src/main/java/com/seb45_main_031/routine/todo/mapper/TodoMapper.java
  server/routine/src/main/java/com/seb45_main_031/routine/todo/repository/TodoRepository.java
  server/routine/src/main/java/com/seb45_main_031/routine/todo/service/TodoService.java
Labels: BE, Refactoring

#148 [BE] Remove: remove todo patch date & savedTodo mapping
  server/routine/src/main/java/com/seb45_main_031/routine/savedTodo/dto/SavedTodoDto.java
  server/routine/src/main/java/com/seb45_main_031/routine/savedTodo/mapper/SavedTodoMapper.java
  server/routine/src/main/java/com/seb45_main_031/routine/todo/dto/TodoDto.java
  server/routine/src/main/java/com/seb45_main_031/routine/todo/mapper/TodoMapper.java
  server/routine/src/main/java/com/seb45_main_031/routine/todo/service/TodoService.java
Labels: Feat, BE, Refactoring

#144 [FE] 컴포넌트 세부 분리 및 디렉토리 페이지 뷰 구현
  FE/src/App.js
  FE/src/assets/images/directoryIcon.png
  FE/src/assets/images/directoryOnclickIcon.png
  FE/src/components/CategoryModal/index.js
  FE/src/components/CloseButton/index.js
  FE/src/components/CommentModal/Buttons.js
  FE/src/components/CommentModal/index.js
  FE/src/components/CommunityEditCalendarModal/Date.js
  FE/src/components/CommunityEditCalendarModal/TodoGroup.js
  FE/src/components/CommunityEditCalendarModal/index.js
  FE/src/components/CommunityEditPost/Buttons.js
  FE/src/components/CommunityEditPost/index.js
  FE/src/components/DeleteConfirmModal/index.js
  FE/src/components/DirectoryButton/index.js
  FE/src/components/DirectoryDetailTitle/index.js
  FE/src/components/DirectoryDetailTodoGroup/index.js
  FE/src/components/DirectoryList/Category.js
  FE/src/components/DirectoryList/index.js
  FE/src/components/DirectoryTitle/index.js
  FE/src/components/EditEmojiModal/index.js
  FE/src/components/EditTipContents/Tips.js
  FE/src/components/EditTipContents/Title.js
  FE/src/components/ErrorModal/index.js
  FE/src/components/FeedCard/Comment.js
  FE/src/components/FeedCard/CommentCreate.js
  FE/src/components/FeedCard/Comments.js
  FE/src/components/FeedCard/ModalButton.js
  FE/src/components/FeedCard/index.js
  FE/src/components/Footer.js
  FE/src/components/Header.js
  FE/src/components/TagModal/Tag.js
  FE/src/components/TagModal/index.js
  FE/src/components/TodoCalendarModal/index.js
  FE/src/components/TodoCard/index.js
  FE/src/components/TodoEditPost/Buttons.js
  FE/src/components/TodoEditPost/Post.js
  FE/src/components/TodoEditPost/Validation.js
  FE/src/components/TodoEditPost/index.js
  FE/src/components/TodoList/index.js
  FE/src/components/TodoModal/Exit.js
  FE/src/components/TodoModal/Todo.js
  FE/src/components/TodoModal/TodoModalButtons.js
  FE/src/components/TodoModal/index.js
  FE/src/components/UserShell/Chart.js
  FE/src/components/UserShell/Date.js
  FE/src/components/UserShell/Filter.js
  FE/src/components/UserShell/User.js
  FE/src/components/UserShell/index.js
  FE/src/pages/CommunityEditPage.js
  FE/src/pages/CommunityModifyPage.js
  FE/src/pages/CommunityPage.js
  FE/src/pages/DirectoryDetailPage.js
  FE/src/pages/DirectoryPage.js
  FE/src/pages/Page.js
  FE/src/pages/TodoEditPage.js
  FE/src/pages/TodoModifyPage.js
  FE/src/pages/todoPage.js
  FE/src/styles/GlobalStyles.js
  FE/src/utils/userTrophy.js
Labels: Feat, FE, Refactoring, Advanced

#146 [FE] Feat & Design: 마이페이지 회원탈퇴 기능 구현, 헤더 및 컴포넌트 크기 조정
  FE/src/components/MyPageHeader.js
  FE/src/pages/MyPageEdit.js
Labels: Feat, FE

#149 [FE] Feat & Refactor: 마이페이지 로그아웃 기능/ 3주차 멘토링 리팩토링/ 컴포넌트 리사이징
  FE/src/pages/MyPage.js
Labels: Feat, FE, Refactoring

#150 [FE] Feat: HomePage에서 LoginPage 자동이동
  FE/src/pages/HomeTest.js
  FE/src/pages/SignUpPage.js
Labels: Feat, FE

#152 [BE] Feat : OAuth2 구현
  server/routine/build.gradle
  server/routine/src/main/java/com/seb45_main_031/routine/auth/config/SecurityConfiguration.java
  server/routine/src/main/java/com/seb45_main_031/routine/auth/handler/OAuth2LoginSuccessHandler.java
  server/routine/src/main/java/com/seb45_main_031/routine/auth/userDetailsService/CustomUserDetailsService.java
  server/routine/src/main/java/com/seb45_main_031/routine/member/entity/Member.java
  server/routine/src/main/java/com/seb45_main_031/routine/member/repository/MemberRepository.java
  server/routine/src/main/java/com/seb45_main_031/routine/member/service/MemberService.java
  server/routine/src/main/resources/application.yml
Labels: Feat, BE, Advanced

#153 [FE] Feat: 마이페이지 로그인, 회원가입 기능 연결
  FE/src/pages/MyPage.js
  FE/src/pages/MyPageEdit.js
Labels: Feat, FE

#155 [FE] Feat: LoginPage Alert 추가
  FE/src/pages/LoginPage.js
Labels: FE

#154 [BE] Feed, Comment 유효성 검증
  server/routine/src/main/java/com/seb45_main_031/routine/comment/dto/CommentDto.java
  server/routine/src/main/java/com/seb45_main_031/routine/comment/entity/Comment.java
  server/routine/src/main/java/com/seb45_main_031/routine/feed/controller/FeedController.java
  server/routine/src/main/java/com/seb45_main_031/routine/feed/dto/FeedDto.java
  server/routine/src/main/java/com/seb45_main_031/routine/feed/entity/Feed.java
  server/routine/src/main/java/com/seb45_main_031/routine/feed/repository/FeedRepository.java
  server/routine/src/main/java/com/seb45_main_031/routine/feed/service/FeedService.java
  server/routine/src/main/java/com/seb45_main_031/routine/feedLike/service/FeedLikeService.java
Labels: Feat, BE, Refactoring

#162 [BE] Feat : Tag Patch 기능 추가
  server/routine/src/main/java/com/seb45_main_031/routine/exception/ExceptionCode.java
  server/routine/src/main/java/com/seb45_main_031/routine/tag/controller/TagController.java
  server/routine/src/main/java/com/seb45_main_031/routine/tag/dto/TagDto.java
  server/routine/src/main/java/com/seb45_main_031/routine/tag/entity/Tag.java
  server/routine/src/main/java/com/seb45_main_031/routine/tag/mapper/TagMapper.java
  server/routine/src/main/java/com/seb45_main_031/routine/tag/service/TagService.java
  server/routine/src/main/resources/application.yml
Labels: Feat, BE

#164 [BE] todo complete refactor & Add memberId, level
  server/routine/src/main/java/com/seb45_main_031/routine/exception/ExceptionCode.java
  server/routine/src/main/java/com/seb45_main_031/routine/todo/dto/TodoDto.java
  server/routine/src/main/java/com/seb45_main_031/routine/todo/mapper/TodoMapper.java
  server/routine/src/main/java/com/seb45_main_031/routine/todo/service/TodoService.java
Labels: Feat, BE, Refactoring

#167 [FE] 전체적인 코드 업데이트
  FE/src/App.js
  FE/src/Layouts/LoginLayout.js
  FE/src/Layouts/ProfileLayout.js
  FE/src/Layouts/RootLayout.js
  FE/src/components/CategoryModal/index.js
  FE/src/components/DirectoryButton/index.js
  FE/src/components/DirectoryTitle/index.js
  FE/src/components/ErrorModal/index.js
  FE/src/components/LoginHeader.js
  FE/src/components/ScrapButtonModal/Buttons.js
  FE/src/components/ScrapButtonModal/index.js
  FE/src/components/ScrapEdit/Buttons.js
  FE/src/components/ScrapEdit/EditButton.js
  FE/src/components/ScrapEdit/Title.js
  FE/src/components/ScrapEdit/index.js
  FE/src/data/constants.js
  FE/src/data/tags.js
  FE/src/pages/CommunityEditPage.js
  FE/src/pages/CommunityModifyPage.js
  FE/src/pages/CommunityPage.js
  FE/src/pages/DirectoryPage.js
  FE/src/pages/LoginPage.js
  FE/src/pages/ScrapTodoEditPage.js
  FE/src/pages/SignUpPage.js
  FE/src/pages/TodoEditPage.js
  FE/src/pages/TodoModifyPage.js
  FE/src/pages/todoPage.js
Labels: Feat, FE, Refactoring, Advanced

#168 [FE] Fix: Login Signup 유효성검사
  FE/src/pages/LoginPage.js
  FE/src/pages/SignUpPage.js
Labels: FE

#171 [BE] Feat : 유효성 검증 추가
  server/routine/src/main/java/com/seb45_main_031/routine/auth/handler/CustomAuthenticationSuccessHandler.java
  server/routine/src/main/java/com/seb45_main_031/routine/exception/ErrorResponse.java
  server/routine/src/main/java/com/seb45_main_031/routine/member/dto/MemberDto.java
  server/routine/src/main/java/com/seb45_main_031/routine/savedTodo/dto/SavedTodoDto.java
  server/routine/src/main/java/com/seb45_main_031/routine/todoStorage/dto/TodoStorageDto.java
Labels: Feat, BE

#172 Feat : Member 유효성 검증 추가
  server/routine/src/main/java/com/seb45_main_031/routine/savedTodo/dto/SavedTodoDto.java
Labels: Feat, BE

#169 [FE] Fix & Refactor: 마이페이지 기능 에러 해결/ 3차 멘토링 리팩토링
  FE/src/pages/MyPage.js
  FE/src/pages/MyPageEdit.js
Labels: Feat, FE, Refactoring

#173 [BE] 피드 좋아요 기능에 대한 동시성 문제
  server/routine/src/main/java/com/seb45_main_031/routine/auth/handler/CustomAuthenticationSuccessHandler.java
  server/routine/src/main/java/com/seb45_main_031/routine/exception/ExceptionCode.java
  server/routine/src/main/java/com/seb45_main_031/routine/feed/entity/Feed.java
  server/routine/src/main/java/com/seb45_main_031/routine/feedLike/service/FeedLikeService.java
Labels: BE, Advanced

#174 [FE] 뷰 개선과 로그인 판독 유틸 추가
  FE/src/App.js
  FE/src/Layouts/LoginLayout.js
  FE/src/Layouts/ProfileLayout.js
  FE/src/Layouts/RootLayout.js
  FE/src/components/Footer.js
  FE/src/components/Header.js
  FE/src/components/LoginHeader.js
  FE/src/components/MyPageHeader.js
  FE/src/components/TodoCalendarModal/index.js
  FE/src/components/TodoCard/index.js
  FE/src/components/TodoModal/Todo.js
  FE/src/components/TodoModal/index.js
  FE/src/components/UserShell/Chart.js
  FE/src/components/UserShell/Filter.js
  FE/src/components/UserShell/User.js
  FE/src/components/UserShell/index.js
  FE/src/data/constants.js
  FE/src/pages/CommunityEditPage.js
  FE/src/pages/CommunityModifyPage.js
  FE/src/pages/CommunityPage.js
  FE/src/pages/DirectoryDetailPage.js
  FE/src/pages/DirectoryPage.js
  FE/src/pages/LoginPage.js
  FE/src/pages/MyPage.js
  FE/src/pages/MyPageEdit.js
  FE/src/pages/ScrapTodoEditPage.js
  FE/src/pages/SignUpPage.js
  FE/src/pages/TodoEditPage.js
  FE/src/pages/TodoModifyPage.js
  FE/src/pages/todoPage.js
  FE/src/styles/GlobalFonts.js
  FE/src/styles/GlobalStyles.js
  FE/src/utils/authLoginCheck.js
  FE/src/utils/userTrophy.js
Labels: Feat, FE, Refactoring, Advanced

#176 [FE] Fix: 비밀번호 유효성 수정
  FE/src/pages/SignUpPage.js
Labels: FE, Refactoring

#182 [BE] Fix: todo refactor member id level
  server/routine/src/main/java/com/seb45_main_031/routine/todo/controller/TodoController.java
  server/routine/src/main/java/com/seb45_main_031/routine/todo/mapper/TodoMapper.java
Labels: BE, Refactoring

#183 [BE] 피드 좋아요 기능에 대한 동시성 문제
  server/routine/src/main/java/com/seb45_main_031/routine/exception/ExceptionCode.java
  server/routine/src/main/java/com/seb45_main_031/routine/feed/dto/FeedDto.java
  server/routine/src/main/java/com/seb45_main_031/routine/feed/entity/Feed.java
  server/routine/src/main/java/com/seb45_main_031/routine/feed/mapper/FeedMapper.java
  server/routine/src/main/java/com/seb45_main_031/routine/feedLike/controller/FeedLikeController.java
  server/routine/src/main/java/com/seb45_main_031/routine/feedLike/entity/FeedLike.java
  server/routine/src/main/java/com/seb45_main_031/routine/feedLike/mapper/FeedLikeMapper.java
  server/routine/src/main/java/com/seb45_main_031/routine/feedLike/service/FeedLikeService.java
Labels: Bug, BE

#180 [FE] Favicon 업데이트 및 발견된 이슈 해결
  FE/public/favicon.ico
  FE/public/index.html
  FE/src/components/FeedCard/Comment.js
  FE/src/components/FeedCard/Comments.js
  FE/src/components/FeedCard/PostContents.js
  FE/src/components/FeedCard/PostUser.js
  FE/src/components/FeedCard/index.js
  FE/src/pages/CommunityPage.js
  FE/src/utils/authLoginCheck.js
Labels: FE

#186 [BE] Feat : 핸들러 메소드 접근 권한 설정
  server/routine/src/main/java/com/seb45_main_031/routine/auth/config/SecurityConfiguration.java
  server/routine/src/main/java/com/seb45_main_031/routine/auth/utils/CustomAuthorityUtils.java
  server/routine/src/main/resources/application.yml
Labels: Feat, BE, Advanced

#198 [FE] Feat: 닉네임 유효성 검사
  FE/src/pages/MyPageEdit.js
Labels: Feat, FE

#197 [FE] Design: 마이페이지 스크롤 추가
  FE/src/pages/MyPage.js
Labels: Bug, FE

#199 [FE] Feat: google page
  FE/src/App.js
  FE/src/pages/GooglePage.js
  FE/src/pages/Page.js
  README.md
Labels: Feat, FE

#202 [FE] Fix: 닉네임 유효성검사 수정
  FE/src/pages/MyPageEdit.js
Labels: Feat, FE

#201 [BE] :recycle: Refactoring : OAuth2 수정 / member 전체조회 삭제 / yml 설정
  server/routine/build.gradle
  server/routine/src/main/java/com/seb45_main_031/routine/auth/config/SecurityConfiguration.java
  server/routine/src/main/java/com/seb45_main_031/routine/auth/handler/OAuth2LoginSuccessHandler.java
  server/routine/src/main/java/com/seb45_main_031/routine/member/controller/MemberController.java
  server/routine/src/main/resources/application.yml
Labels: BE, Refactoring, Advanced

#203 [FE] Feat: 구글 OAuth 로그인, 마이페이지 스크롤 및 닉네임 유효성 검사
  FE/src/App.js
  FE/src/pages/GooglePage.js
  FE/src/pages/MyPage.js
  FE/src/pages/MyPageEdit.js
  FE/src/pages/Page.js
  server/routine/build.gradle
  server/routine/src/main/java/com/seb45_main_031/routine/auth/config/SecurityConfiguration.java
  server/routine/src/main/java/com/seb45_main_031/routine/auth/handler/OAuth2LoginSuccessHandler.java
  server/routine/src/main/java/com/seb45_main_031/routine/member/controller/MemberController.java
  server/routine/src/main/resources/application.yml
Labels: Feat, FE

#204 [FE] Fix: 닉네임 변경 로직 수정
  FE/src/pages/MyPageEdit.js
Labels: Bug, FE

#205 [FE] Fix: 할일목록 페이지 파일명 변경, 닉네임 변경 로직 수정
  FE/src/pages/MyPageEdit.js
  FE/src/pages/TodoPage.js
Labels: Bug, FE

#208 [BE] Modify : Google OAuth2 중복이름 변경
  server/routine/src/main/java/com/seb45_main_031/routine/auth/handler/OAuth2LoginSuccessHandler.java
Labels: BE, Modify

#210 [BE] Modify : Member 이미지 관련 변경 사항
  server/routine/src/main/java/com/seb45_main_031/routine/auth/config/SecurityConfiguration.java
  server/routine/src/main/java/com/seb45_main_031/routine/member/controller/MemberController.java
  server/routine/src/main/java/com/seb45_main_031/routine/member/dto/MemberDto.java
  server/routine/src/main/java/com/seb45_main_031/routine/member/mapper/MemberMapper.java
  server/routine/src/main/java/com/seb45_main_031/routine/member/service/MemberService.java
  server/routine/src/main/java/com/seb45_main_031/routine/tag/controller/TagController.java
Labels: BE, Modify
